### ISSUE TITLE
Repository Maintenance

### ISSUE THREAD

**Issue by PhoneDroid** [daweedkob/sorting_algos#1]
I would recommend to disable unused features in this repository, as well as your other ones.

For this repository that would be the

- Projects

- Releases

- Packages

- Environments

  *While yes, one is shown, it would be better to just place the link in the repository 'website' field*

**Comment by daweedkob** [comment]
Thanks for pointing that out. Done.

**Comment by PhoneDroid** [comment]
Wow instant response, impressive O.O
