### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by PhoneDroid** [daweedkob/sorting_algos#2]
As you seem to be active, I wanted to propose to refactor the code.

I would open a draft PR, so you'll be able to follow my progress.

**Comment by daweedkob** [comment]
Please don't try refactoring anything. If you have another approach to solving the problem you can add your code in a new file with the same name + `_N` so others can take a look at both versions.
Example:
`10.py` -> `10_2.py` -> `10_3.py` -> `...`

**Comment by PhoneDroid** [comment]
> Please don't try refactoring anything. 

I'm confused, why wouldn't I want to improve the existing code but instead create a separate solution?

**Comment by daweedkob** [comment]
The project is created for learning purposes, if we keep all the versions we can learn more (why the other solution was bad or better)

**Comment by PhoneDroid** [comment]
Sorry, isn't that what a commit history is for?

I you wanted to compare them, you could
simply add a link to the current ( then previous )
commit branch, effectively resulting in the same
with less code duplication.

**Comment by PhoneDroid** [comment]
Plus that way you could use GitHubs built-in comparison features as well.

**Comment by daweedkob** [comment]
Personally, I prefer separate files.

**Comment by PhoneDroid** [comment]
Would separate branches also work?

**Comment by daweedkob** [comment]
Sure
